### PR TITLE
add commonjs as extend file

### PR DESCRIPTION
**Pull request by sveisvei**

### CODE REVIEW

**Comment by SimenB** [comment]
What's the diff with this and `finn/node`?

Use case, I mean, I get that rules are different 😄

**Comment by sveisvei** [comment]
node includes all kinds of more "stuff" than module and exports :). But if its only this key/prop for es5 commonjs browser modules im not sure its needed.

**Comment by gregersrygg** [comment]
Why should we allow commonjs for browser modules when they can use ES modules?

**Comment by sveisvei** [comment]
Allow for new stuff, no, but for old stuff. BUT, closing this, likely yagni.

**Pull request closed without merging**
